version: '3'

services:
  mailpit:
    image: axllent/mailpit
    container_name: task-manager-mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  redis:
    image: redis:7-alpine
    container_name: task-manager-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    environment:
      - REDIS_PASSWORD=
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  email-worker:
    build:
      context: .
      dockerfile: apps/email-worker/Dockerfile
    container_name: task-mgmt-email-worker
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
      - MAIL_USER=
      - MAIL_PASS=
      - NODE_ENV=development
    depends_on:
      - redis
      - mailpit

  # payload:
  #   build: .
  #   container_name: payload
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3000
  #     - DATABASE_URL=
  #     - PAYLOAD_SECRET=
  #     - NEXT_PUBLIC_SERVER_URL=

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  data:
  pgdata:
  redis_data:
