version: '3'

services:
  mailpit:
    image: axllent/mailpit
    container_name: task-manager-mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  redis:
    image: redis:latest
    container_name: task-manager-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always

  # payload:
  #   build: .
  #   container_name: payload
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3000
  #     - DATABASE_URL=
  #     - PAYLOAD_SECRET=
  #     - NEXT_PUBLIC_SERVER_URL=

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  data:
  pgdata:
  redis_data:
