name: Weekly Version Bump

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
        env:
          CI: true

      # pnpm up --latest -r
      - name: Update dependencies
        run: pnpm up --latest -r && pnpm install

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected after dependency updates"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected after dependency updates"
          fi

      - name: Bump versions
        if: steps.changes.outputs.has_changes == 'true'
        run: pnpm version patch -r --no-git-tag-version

      - name: Create pull request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: weekly version bump and dependency updates'
          branch: chore/weekly-version-bump
          title: 'chore: weekly version bump and dependency updates'
          body: "## Summary\n- Weekly version bump\n- Updated dependencies to latest versions"
          base: main
